### ISSUE TITLE
Plans for NEW Docker API

### ISSUE THREAD

**Issue by Vad1mo** [yholkamp/ovh-docker-volume-plugin#2]
I tried the plugin yesterday and it worked as expected. Even mounting the same volume across multiple VMs worked.

However it was a bit of a hassle to make it run. When compared to 
https://github.com/sapk/docker-volume-gluster where its only a one liner.

Are they any plans to upgrade to the new API Version as announced in the TODO?

**Comment by yholkamp** [comment]
@Vad1mo as I commented in the other ticket, thanks for giving the plugin a shot! As you've seen by now, I haven't been actively developing this plugin. A while back I've moved my database instances out of docker, eliminating my need for this plugin so I do not currently have plans to upgrade this plugin to the newer API in the near future. I'm happy to accept pull requests but I don't have the time to spare for this upgrade at the moment.
